  targetConfigs:
- url: https://github.com/ubiquitous-factory/ai-remote-edge
  branch: main
    raw:
    - name: serial-reader-deploy
      targetPath: deploy/serial-reader
      schedule: "*/1 * * * *"